#!/bin/sh
# Writes report.txt summarising the .txt files beside this script.
set -e
cd "$(dirname "$0")"
{
  echo "files: $(ls -1 *.txt 2>/dev/null | grep -v '^report.txt$' | wc -l | tr -d ' ')"
  echo "generated by make-report.sh"
} > report.txt
echo "wrote report.txt"
